language: python
python:
  - "2.7"

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
    - yasm
    - g++-4.8

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install algo/brotli_src
  - yasm algo/paq8l_src/paq7asm-x86_64.asm -f elf -m amd64 -o algo/paq8l_src/paq7asm-x86_64.o
  - g++ algo/paq8l_src/paq8l.cpp -DUNIX -O2 -Os -s -fomit-frame-pointer -o algo/paq8l algo/paq8l_src/paq7asm-x86_64.o
  - chmod +x $TRAVIS_BUILD_DIR/algo/ppmd_src/ppmd
  - ln -s $TRAVIS_BUILD_DIR/algo/ppmd_src/ppmd $TRAVIS_BUILD_DIR/algo/ppmd

# command to run tests
script:
  - py.test --cov=tools
after_success:
  - coveralls
env:
  - PATH=$PATH:$TRAVIS_BUILD_DIR/algo/